"""followers

Revision ID: 688fe041debf
Revises: f8c2676d8c44
Create Date: 2021-02-02 19:17:13.603345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '688fe041debf'
down_revision = 'f8c2676d8c44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
